services:
  tg-bot:
    build:
      dockerfile: docker/Dockerfile
      context: .
    container_name: tennis_telegram_bot
    env_file:
      - ./docker/backend/.env
    depends_on:
      - postgresql
    volumes:
      - ./src:/app/src
    command: ["entrypoint"]

  postgresql:
    image: postgres
    container_name: tennis_telegram_db
    ports:
      - "5432:5432"
    env_file:
      - ./docker/postgresql/.env
