version: "3"

services:
  bot:
    build:
      dockerfile: system/Dockerfile
      context: .
    container_name: tennis_telegram_bot
    env_file:
      - ./docker/backend/.env
    restart: always
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.6
    container_name: tennis_mariadb
    ports:
      - "3306:3306"
    env_file:
      - ./docker/mariadb/.env
    restart: always
