services:
  bot:
    build:
      dockerfile: system/Dockerfile
      context: .
    container_name: tennis_telegram_bot
    env_file:
      - ./docker/backend/.env
    depends_on:
      - postgresql
      - loki
      - promtail

  postgresql:
    image: postgres
    container_name: tennis_telegram_db
    ports:
      - "5432:5432"
    env_file:
      - ./docker/postgresql/.env

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    user: "root"
    volumes:
      - ./docker/loki/config:/etc/loki
      - ./docker/loki/wal:/wal

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - ./docker/promtail/config:/etc/promtail
    command: -config.file=/etc/promtail/promtail-config.yaml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./docker/grafana/data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_DISABLE_LOGIN_FORM=false
    depends_on:
      - loki
