FULL_NAME_COLUMN_WIDTH = 20
NUMBER_OF_TRAINING_AT_THE_START_OF_MONTH_COLUMN_WIDTH = 20
PAYMENT_AMOUNT_COLUMN_WIDTH = 15
PAID_TRAINING_SESSIONS_COLUMN_WIDTH = 20
DATE_OF_PAYMENTS_COLUMN_WIDTH = 15
EMPTY_COLUMN_WIDTH = 15
NUMBER_OF_TRAINING_AT_THE_END_OF_MONTH_COLUMN_WIDTH = 35
